Test Suite for session service
WiiQare/backend pull request #48
Opened 2023-06-13 15:02 UTC by lukebrichey

## Description

In this pull request, I have added a comprehensive test suite for the `session` module, which should greatly increase the test coverage of the codebase. This is in-line with the requirements of our Q3 open source work.

The newly incorporated test suite is in the `session.service.test.ts` file and encompasses tests for each method available in the session service. These methods include:
- `authenticateUser`
- `findOne`
- `emailVerification`
- `validateEmailOTP`
- `isValidOTP`
- `hashDataToHex`
- `generateEmailVerificationHash`
- `resetPassword`
- `updatePassword`

Additionally, a minor refactor in the `payer-svc` module  and `session.service.ts` file is included in this PR, updating several import paths to use relative paths for compatibility with Jest.

## Changes
- Incorporation of a new test suite in `session.service.test.ts` for the Session Service.
- Refactoring of some import paths in `payer-svc` module and `session.service.ts` file to relative paths.

## Notes for Reviewers
Please review the added test suite to confirm that it accounts for all the relevant test cases and conditions for the session service. Also, verify that the modified import paths I have included in this PR does not interfere with the functionality of the `payer-svc` module.

2023-06-14 06:44 UTC, abhiShandy requested changes
missing test coverage for lines 108-113

2023-06-14 06:47 UTC, abhiShandy commented
you can run `yarn test --coverage` and look for the appropriate file in the report table to find missing coverage.

<img width="717" alt="Screenshot 2023-06-14 at 2 47 28 AM" src="https://github.com/WiiQare/backend/assets/6998593/f17112b0-0c92-4e33-971b-cb1119aba3e3">

2023-06-14 14:31 UTC, lukebrichey commented
I just added a commit with changes to incorporate the feedback. Thanks for reviewing and the helpful tip!

2023-06-15 01:40 UTC, abhiShandy approved these changes

2023-06-15 01:40 UTC, merged